# Generated by Django 5.2.1 on 2025-05-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0008_alter_scholarship_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='provider',
            field=models.CharField(default='Unknown Provider', max_length=200),
        ),
    ]
