# Generated by Django 5.2.1 on 2025-05-30 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0009_scholarship_amount_scholarship_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='provider',
        ),
    ]
