# Generated by Django 5.2.1 on 2025-05-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0010_remove_scholarship_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='provider',
            field=models.CharField(default='Unknown Provider', max_length=200),
        ),
    ]
