# Generated by Django 5.1.7 on 2025-12-23 15:22

import uuid
from django.db import migrations, models


def generate_unique_uuids(apps, schema_editor):
    """Generate unique UUIDs for existing scholarships"""
    Scholarship = apps.get_model('scholarships', 'Scholarship')
    for scholarship in Scholarship.objects.all():
        if not scholarship.uuid:
            scholarship.uuid = uuid.uuid4()
            scholarship.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0012_scholarship_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True, blank=True),
        ),
        migrations.RunPython(generate_unique_uuids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='scholarship',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scholarships/'),
        ),
    ]
