# Generated by Django 5.2.1 on 2025-12-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0013_scholarship_uuid_alter_scholarship_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='uuid',
        ),
    ]
