# Generated by Django 5.2.1 on 2026-05-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0013_alter_scholarship_image'),
        ('scholarships', '0015_scholarship_slug'),
    ]

    operations = [
    ]
