# Generated by Django 5.2.1 on 2025-06-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='verification_type',
            field=models.CharField(choices=[('email_verification', 'Email Verification'), ('password_reset', 'Password Reset')], default='email_verification', max_length=20),
        ),
    ]
